version: '3.4'

services:
  grafana:
    container_name: grafana
    image: ghcr.io/volkovlabs/app:latest
    ports:
      - 3000:3000/tcp
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_ENABLE_GZIP=true
      - GF_DEFAULT_APP_MODE=development
    volumes:
      - ./dist:/var/lib/grafana/plugins/volkovlabs-abc-app
      - ./provisioning:/etc/grafana/provisioning
      # Uncomment to preserve Grafana configuration
      # - ./data:/var/lib/grafana

  nginx:
    container_name: nginx
    build: ./nginx
    restart: always
    environment:
      - GRAFANA_HOST=host.docker.internal
    ports:
      - 80:80/tcp
      - 443:443/tcp
    depends_on:
      - grafana
