version: '3.4'

services:
  grafana:
    container_name: grafana
    image: ghcr.io/volkovlabs/app:latest
    ports:
      - 3000:3000/tcp
    environment:
      - GF_DEFAULT_APP_MODE=development
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/home.json
    volumes:
      - ./dist:/var/lib/grafana/plugins/volkovlabs-abc-app
      - ./provisioning:/etc/grafana/provisioning

  nginx:
    container_name: nginx
    build: ./nginx
    restart: always
    environment:
      - GRAFANA_HOST=host.docker.internal
    ports:
      - 80:80/tcp
      - 443:443/tcp
    depends_on:
      - grafana
